[project]
name = "fascioschoolbot"
version = "0.1.0"
description = "Бот администратор школы фасциопатии Шевкунова А. А."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bestconfig>=1.3.6",
    "pyrogram>=2.0.106",
    "tgcrypto>=1.2.5",
]
